CompileFlags:
  Add: [
    -xc, -std=gnu11,
    -Wall, -Wextra, -Werror,
    -Wshadow, -Wunder, -Wunreachable-code,
    -Wpointer-aritch, -Wcast-align, -Wcast-qual,
    -Wstrict-prototypes, -Wstrict-overflow=5,
    -Wwrite-strings, -Wconversion,
    -Wswitch-default, -Wswitch-enum,
    -Wuninitialized, -Winit-self
    ]
  Remove: -W*
  Compiler: gcc
